apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-profile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-profile
  template:
    metadata:
      labels:
        app: nginx-profile
    spec:
      containers:
        - name: profile-app-container
          image: "image-registry.openshift-image-registry.svc:5000/pavanipp/my-nginx-profile:1.0"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-profile-app-service
spec:
  selector:
    app: nginx-profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
